<a href="https://colab.research.google.com/github/Umme44/Pytprch-Tutorials/blob/main/Pytorch_tutorials_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


###Initilize a tensor

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

In [8]:
print(zero_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##Attribute of Tensor

In [9]:
tensor = torch.rand(2,3)
print("Shape of Tensor : ",{tensor.shape})
print("dtype of Tensor : ",{tensor.dtype})
print("device of Tensor : ",{tensor.device})


Shape of Tensor :  {torch.Size([2, 3])}
dtype of Tensor :  {torch.float32}
device of Tensor :  {device(type='cpu')}


##Operations In Tensors

In [10]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

##Indexing and Slicing

In [17]:
tensor = torch.ones(4,4)
print(f"First row: ",tensor[0])
print(f"First column: ",tensor[:,0])
print(f"last row: ",tensor[...,-1])
tensor[:1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
last row:  tensor([1., 1., 1., 1.])
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


##joining tensor

In [16]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
